### ISSUE TITLE
Relative links seem broken

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#311]
```
reported in rst2pdf-discuss by zer0-droids:

http://groups.google.com/group/rst2pdf-
discuss/browse_thread/thread/efc405aba6235016

Test case coming up.
```

Original issue reported on code.google.com by `roberto.alsina` on 7 Apr 2010 at 2:08

**Comment by nathanjsmith** [comment]
This is still an issue. The 311 test case does use a relative path in the rst, but the generated PDF has an absolute path in the link. I tried manually updating the absolute path in the PDF's URI command to be a relative path, but PDF viewers still see the file:// path as being absolute. If you drop the file:// protocol from the relative path, then some PDF viewers will follow it, but at least evince on CentOS 6 opens it in Firefox, which tries to turn the local path into a web address. Acrobat and Firefox also complain about security risks with the local URI.

Looking at the PDF specification, I believe that the GoToR command should be used for linking across PDF documents and the Launch command used for linking to other types of documents (HTML, docx, etc.). I tried manual updating my PDF with those commands and they seemed to work in general in my tests.

Incidentally, the Sphinx multidoc test generates a PDF that uses the GoToR command, so that might help as a starting point for a fix.
