### ISSUE TITLE
wordaxe - blocker for Python 3?

### ISSUE THREAD

**Issue by oz123** [rst2pdf/rst2pdf#585]
Can we port this to Python 3 ? 
Shall we replace with https://pypi.python.org/pypi/Pyphen?

This needs evaluation and discussion.

**Comment by ralsina** [comment]
I can probably port it when needed, no problem.

**Comment by lornajane** [comment]
What did we do about this? The codebase works on Python 3 so I guess this wasn't a blocker ... can we close the issue or is there more to do?

**Comment by akrabat** [comment]
> What did we do about this? The codebase works on Python 3 so I guess this wasn't a blocker ... can we close the issue or is there more to do?

@ralsina forked Wordaxe to make it work with recent versions of ReportLab here: https://github.com/ralsina/wordaxe. (We also [documented](https://github.com/rst2pdf/rst2pdf/blob/master/doc/manual.rst#14hyphenation) this.)

I do not know if Roberto's Wordaxe works with Python3 or not though as I have no clue if we have a test for it :)

[test_issue_99](https://github.com/rst2pdf/rst2pdf/blob/master/rst2pdf/tests/input/test_issue_99.txt) references Wordaxe, but doesn't appear to have any hyphens in the output PDF, so maybe?

I think that the next step with this issue is to create a test that explicitly hyphenates a word at the end of a line in a paragraph of text and see if it works.

**Comment by stephenfin** [comment]
Perhaps it's just me, but I'm not able to install any version of `wordaxe` from PyPI, which is weird because [it's listed](https://pypi.org/project/wordaxe/) but `pip install` fails. I think we've got a few options here:

- Request ownership of the `wordaxe` project on PyPI and publish a new release based on @ralsina 's fork

    It's the good community thing to do, but it's potentially a lot of work. The code base looks to be in poor shape, even if it is small.

- Switch to another hyphenation library

    Options [are pretty thin on the group](https://pypi.org/search/?q=hyphen) and what's there appear to be unmaintained.

- Vendor `wordaxe`

    Take what we need from `wordaxe`, preserving the license, and dump the rest. Also potentially lots of work and upsetting for distro maintainers who don't like people vendoring things.

- Drop support for hyphenation

    Least amount of work and we could re-add this in the future, but for now we'd lose a feature that worked at some point in the past.

My clear preference would be the last option, simply because I don't particularly care about hyphenation right now and I think our efforts would be better focused elsewhere. It's not my call to make though.

**Comment by ralsina** [comment]
If you find a bug in my fork I am willing to fix it.

I do use hyphenation, but since I am not very active in the project anymore
I have no vote.

**Comment by stephenfin** [comment]
> If you find a bug in my fork I am willing to fix it. I do use hyphenation, but since I am not very active in the project anymore I have no vote.

I think the key issue is that it's not published on PyPI and therefore is not easily installable. One would need to install from source. I assume you don't have access to the GitHub project? Would it be worth reaching out to the original author?

**Comment by ralsina** [comment]
No idea and I am not doing it.

**Comment by lornajane** [comment]
It looks like we already have a fork of the wordaxe code (I'm guessing this would be from @ralsina 's fork anyway but I can check) in this org https://github.com/rst2pdf/wordaxe. Can/should we use this as our dependency?

Definitely would be excellent to get a test where we can see this working, if we know what working would look like!

**Comment by lornajane** [comment]
Update: no, our wordaxe isn't from Roberto's fork and his looks better (like, it's had updates in the last decade). I can also try to find out about getting control of the pypi project if we think we'd like to publish this ourselves, but let me know.

**Comment by stephenfin** [comment]
> Update: no, our wordaxe isn't from Roberto's fork and his looks better (like, it's had updates in the last decade). I can also try to find out about getting control of the pypi project if we think we'd like to publish this ourselves, but let me know.

I've reached out to the wordaxe author to ask about maintainership of the PyPI project. Will update if/when I hear anything back.

**Comment by akrabat** [comment]
I'm in favour of having a hyphenation solution as it just looks better for paragraphs of text. 

We have a wordaxe fork that works, so that's the path of least resistance. It feels like we should get that into PyPI and the most polite way to do that is talk to the current PyPI project and take it over. If that's not possible, I suppose we can invent a new name and publish with that.

We definitely should have a test too, if don't already have one.

**Comment by akrabat** [comment]
Mind you, I think recent ReportLabs may already support hyphenation.

From https://www.reportlab.com/docs/reportlab-userguide.pdf:

> If the pyphen python module is installed attribute `hyphenationLang` controls which language will be used to hyphenate words without explicit embedded hyphens.
> If `embeddedHyphenation` is set then attempts will be made to split words with embedded hyphens.

**Comment by akrabat** [comment]
Okay, I've tested this now.

Firstly, I installed pyphen with: `pip3 install pyphen`

Then:

test_hyphenation.rst:

```rst

**Comment by akrabat** [comment]
So, the action we need to take it so update the manual!

**Comment by akrabat** [comment]
PR #887 removes wordaxe.
Issue #888 is for updating the manual.
