### ISSUE TITLE
this raises a SyntaxError for python3.+

### ISSUE THREAD

**Issue by vchernetsov** [rst2pdf/rst2pdf#636]
https://github.com/rst2pdf/rst2pdf/blob/26792a4edfc0309ad57c0d334f17fbf856ce6228/rst2pdf/pdfbuilder.py#L129

**Comment by akrabat** [comment]
rst2pdf is a Python 2 project at the moment.

**Comment by paugier** [comment]
Thank you for rst2pdf !

Wouldn't it be a good time to work on a py2/3 compatible version (https://pythonclock.org/)? With the package [future](http://python-future.org/futurize.html), it can be not so difficult. 

First, "simple" transformations:

```bash
  futurize --stage1 -w rst2pdf/**/*.py
  futurize --stage2 -w rst2pdf/**/*.py
```

Then, one has to take care of the byte and unicode, which is less simple since choices have to be made. All unicode may be ok for rst2pdf?

**Comment by akrabat** [comment]
Updating for Python 3 is definitely planned. We need to get all the unit tests passing with latest python 2 and latest reportlab first, though.

**Comment by Kilo59** [comment]
There's a few other examples in this file.

https://github.com/rst2pdf/rst2pdf/blob/26792a4edfc0309ad57c0d334f17fbf856ce6228/rst2pdf/pdfbuilder.py#L849

For Python3: `except ImportError as e:`

https://github.com/rst2pdf/rst2pdf/blob/26792a4edfc0309ad57c0d334f17fbf856ce6228/rst2pdf/pdfbuilder.py#L826

For Python3: `except (SyntaxError, UnicodeEncodeError) as e:`

**Comment by akrabat** [comment]
Closing as we know Python 3 is not yet supported.
