### ISSUE TITLE
Snapcraft release

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#743]
I went to a lightning talk at FOSDEM on [Snapcraft](https://snapcraft.io) and I think we need to be here and probably in other app-stores if there are any others? 

As I understand it, Snapcraft allows users to update to the latest version of rst2pdf when the version provided by apt is out of date. It seems that most users are on LTS versions of Ubuntu and so they won't get the latest rst2pdf from apt. i.e. Snapcraft decouples rst2pdf's release cycle from Ubuntu's for users.

I also wonder if it allows us to also package up our dependencies like ReportLab independently of the system's. This would ensure that a user who is using our rst2pdf _snap_ won't get any weird incompatibility issues if they updated the system ReportLab to one we don't work with.

The obvious tasks for this ticket:

1. Investigate how to create a snap and then write the code/scripts to create it.
2. Investigate how to create an account on Snapcraft for the project and get this set up.
3. Implement a way to create snaps when Travis builds _master_ so that we can have an automated "latest dev" version in the snapcraft store.
4. Document how to create a tagged version release snap for [RELEASE_PROCESS.rst](https://github.com/rst2pdf/rst2pdf/blob/master/doc/RELEASE_PROCESS.rst)

**Comment by ralsina** [comment]
Good news, I used to work in snap-related things at canonical a while ago!
:-)

Creating a snap for st2pdf should be pretty simple. However!

snaps for command line tools like this one have, to be useful, to be
"classic" mode, meaning it's a tool that can read and write from the user's
home directory. For more information see this:
https://snapcraft.io/blog/demystifying-snap-confinement

The problem is that "classic" confinement is not granted lightly for apps
in the store. I know because I asked for it for another tool and didn't get
it.

**Comment by lornajane** [comment]
This is super interesting! @ralsina is it that the app has to be either "classic", and therefore gets access to all files or "strict" and have access to none? Is there nothing for being able to work with the file names the user supplied when running the command or something? I don't remember if rst2pdf also writes intermediate files as well as the PDF file output.

**Comment by ralsina** [comment]
On Tue, Feb 12, 2019 at 12:53 PM Lorna Jane Mitchell <
notifications@github.com> wrote:

> This is super interesting! @ralsina <https://github.com/ralsina> is it
> that the app has to be either "classic", and therefore gets access to all
> files or "strict" and have access to none? Is there nothing for being able
> to work with the file names the user supplied when running the command or
> something? I don't remember if rst2pdf also writes intermediate files as
> well as the PDF file output.
>
>
The "strict" sandboxing prevents access to $HOME so it makes rst2pdf a bit
hard to use.
It can access a specific folder (something like ~/sandbox/rst2pdf) and a
folder for temporary files (I think rst2pdf creates all temp files properly
so that is ok).

A "classic" sandboxed app basically has access to files as normal apps
installed via apt or whatever, according to permissions.

This may have changed since I last checked this out a couple of years ago,
of course.

**Comment by akrabat** [comment]
A quick read implied that there is something called "interfaces" that look similar to macOS's "entitlements" that are used to grant permissions to "strict" apps. I didn't read any further than that as I'm confident that whoever takes on this ticket will do that :)

**Comment by lornajane** [comment]
Looks like the interface is `personal-files` https://docs.snapcraft.io/the-personal-files-interface/9357 but it's really new. I've asked a question on their forum to try to get a better handle on whether we want to proceed with this or not.

**Comment by lornajane** [comment]
@popey please can you lend a hand with this?

**Comment by lornajane** [comment]
@ralsina did you register the `rst2pdf` snap name on the snapcraft.io store? I will need it to be able to publish the snap. If it wasn't you, I can request it be released to me.

**Comment by lornajane** [comment]
I've requested the rst2pdf name be released to me so we can merge this and get the snap available
