### ISSUE TITLE
Py3k error with "unicode" identifier in dotted_toc extension

### ISSUE THREAD

**Issue by pakal** [rst2pdf/rst2pdf#815]
I've seen port to py3K is in progress, thanks a lot for that!

Just in case, I tried launching my pdf build on today's rst2pdf github master, under python3.7.3, it failed due to this line:

```
Traceback (most recent call last):
  File "....a\lib\site-packages\reportlab\platypus\flowables.py", line
700, in wrap
    W,H = _listWrapOn(self._content,aW,self.canv,dims=dims)
  File "....\lib\site-packages\reportlab\platypus\flowables.py", line
624, in _listWrapOn
    w,h = f.wrapOn(canv,availWidth,0xfffffff)
  File "....\lib\site-packages\reportlab\platypus\flowables.py", line
125, in wrapOn
    w, h = self.wrap(aW,aH)
  File "....\lib\site-packages\rst2pdf\extensions\dotted_toc.py", line 137, in wrap
    if not isinstance(text, unicode):
NameError: name 'unicode' is not defined
```

Maybe there is a need for a global search-replace of "unicode" with six utility, to batch-solve this kind?

**Comment by tbpassin** [comment]
Here's a simple way around this problem, along with a couple of others )Ihave found in the code:

```
# rst2pdf hacks for python 3+
unicode = type(str) # all strings in Python 3 are unicode.
unichr = chr # Python 3 equivalent.
basestring = str # see https://www.atemon.com/blog/python-3-unexpected-exception-name-basestring-is-not-defined-when-invoking-ansible2/
```

Add these statements to the top of the module that is failing, after the imports.  Better would be to make these definitions conditional on the Python version, something like this:
```
try:
   basestring
except NameError:
   basestring = str
```

**Comment by akrabat** [comment]
Thanks. Do you fancy having a go at creating a PR with a test case for this?

**Comment by tbpassin** [comment]
Well, all right.  It will take some time, since I have to understand how you do the test cases, and then come up with them.   A quick search in the source tree came up with 14 files that use the *unicode* keyword.  So there will be some work for me to do.

Is there a branch specifically for Python 2 to 3 conversions?  If there isn't, it might be a good idea to start one.   I couldn't tell from the names of the branches listed at GitHub. I've worked through 13 files so far, fixing import issues and routine 2to3 issues like ``print()`` vs ``print`` and ``Exception as e`` vs ``Exception, e``.   At least they can now be imported - who knows if they work properly, though.

With a dedicated branch, it would be easier to focus on these 2 to 3 issues.

**Comment by akrabat** [comment]
The only long lived branches we have at the moment are `master` & `0.94.x`. The remainder are branches that were used for specific work; I'll tidy them up and remove them at some point.

My view is that you should fork the repository and create a new branch for your work. Push this to your own origin and then raise a Pull Request against rst2pdf/master.

**Comment by lornajane** [comment]
I'll also chime in: `master` should work with both python2 and python3 - I think we're intending to get one release out for both versions and then focus new development on python3. So master is kind of the branch for python3 work, we run tests on that for 3.6 and 3.7

**Comment by tbpassin** [comment]
I'm at a disadvantage here because haven't done any of these things with Git before.  Last year, Raymond Chen ("The Old New Thing") had a series on how to handle tricky situations in Git.  E.g., https://devblogs.microsoft.com/oldnewthing/20180312-00/?p=98215.

This left me thinking that any significant changes should be developed in separate branches, and that in many cases they should be merged into yet a different merge base before going into Master.   But maybe most of those branches should be my own private ones.

So I'm thinking that I should clone Master onto my computer, start a new branch, and when it's ready, send it back up to GutHub, where someone else will handle merging it into Main or some other branch.  Does this sound right?

And I still think there should be a dedicated branch for handling 2 to 3 issues separate from other bug fixes.

More guidance will be welcome!

**Comment by akrabat** [comment]
I wrote https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/ a few years ago which I think is a good starting point if you're new to contributing to an OSS project on GitHub. If you have any questions, just ask.

In general, yes, each branch that you create to be merged to the project via a pull-request should fix one thing (or a small set of related things) as this is much easier to review and merge.

**Comment by tbpassin** [comment]
Thanks for that, it's very helpful.  Here's a practical question about writing a test case.  For Python 2 - 3 work, all changes should be tested with Python 2 as well as Python 3.  How should I indicate this in the test case?  For my own work, I alias Python 3.8 to py38, etc.  How do you like to do this for rst2pdf?

**Comment by akrabat** [comment]
The way the tests work is documented in [DEVELOPERS.rst](https://github.com/rst2pdf/rst2pdf/blob/master/doc/DEVELOPERS.rst#running-tests).

**Comment by lornajane** [comment]
I _think_ we're fully python3 compatible at this point so this should be solved. Going to close but if anyone has more information please do comment!
