### ISSUE TITLE
Replace rson with something more broadly adopted

### ISSUE THREAD

**Issue by stephenfin** [rst2pdf/rst2pdf#876]
rst2pdf styles are formatted in a special syntax known as [RSON](https://code.google.com/archive/p/rson/). RSON as a standard was effectively a non-starter and appears to be abandoned. There does not appear to be a good reason to retain this format and I'd like to explore switching to a more standard format. There are a great many markup formats available that would be fit for purpose (and many that are not - JSON and XML are both too verbose and difficult to write for humans). I personally think TOML or YAML would be good options.

To compare, consider this snippet taken from `rst2pdf/styles/murphy.style`:

```
styles:
    pygments-bp: {parent: code, textColor: #007020}
    pygments-c:
        fontName: stdMonoItalic
        parent: code
        textColor: #606060
    pygments-c1:
        fontName: stdMonoItalic
        parent: code
        textColor: #606060
    pygments-cm:
        fontName: stdMonoItalic
        parent: code
        textColor: #606060
```

# YAML

YAML is essentially identical to RSON and would make for an easier transition. The `pyyaml` library looks like a good option. However, the YAML spec is notoriously complex and it can be difficult to parse. This likely isn't an issue here but it's worth noting.

```yaml
---
styles:
  pygments-bp: {parent: code, textColor: #007020}
  pygments-c:
    fontName: stdMonoItalic
    parent: code
    textColor: "#606060"
  pygments-c1:
    fontName: stdMonoItalic
    parent: code
    textColor: "#606060"
```

# TOML

TOML is much simpler than YAML and would allow us to integrate with the `pyproject.toml` file introduced in [PEP-518](https://www.python.org/dev/peps/pep-0518/). However, it's quite different from RSON and would require more effort on the users behalf to migrate styles.

```toml
[styles]

  [styles.pygments-bp]
  parent = "code"
  textColor = "#007020"

  [styles.pygments-c]
  fontName = "stdMonoItalic"
  parent = "code"
  textColor = "#606060"

  [styles.pygments-c1]
  fontName = "stdMonoItalic"
  parent = "code"
  textColor = "#606060"
```

---

Personally, I would prefer TOML if we were starting from scratch or if we provided solid documentation (or even a tool) to migrate styles. However, YAML might be the more expedient option. Heck, why not even do both?

**Comment by akrabat** [comment]
I'm pretty sure that rst2pdf also supports JSON, but agree that JSON is not a good choice for human-edited files.

RSON doesn't have widespread support, so I can see the argument for picking something that people actually use.

I'm not especially fussed about the the choice of format. YAML does have a lot of edge-cases, though we're unlikely to run into them. I wonder if that makes the parsing slower and more prone to issue though?

I  do have a _lot_ of RSON style files (`find` suggests that I have in the order of 700). So, whatever we move to, I would be in favour of a conversion tool!

**Comment by lornajane** [comment]
I think yaml would be sensible here since:
- the style files are, or nearly are, valid yaml already so it's probably the line of least resistance!
- yaml is widely used and probably familiar (does that make it great? no ..... but familiar is good)
- the hardest thing about yaml is getting the indentation right but python people can handle that part!

**Comment by lornajane** [comment]
Also probably worth pointing out that we have a ticket open for updating the code styles #761 that should probably wait for a decision here

**Comment by nfraprado** [comment]
I'm for YAML since:
1. RSON is basically YAML. The `---` at the beginning is optional, so we could leave that off. The only difference I could see is that ` #` is a comment (btw, the YAML example in this thread is invalid for this reason), so the conversion tool could be as simple as quoting all color values, that is: `sed -E -e 's/(#[a-fA-F0-9]{6})/"\1"/g'`. This is great since there's less room for errors.
2. The main use for stylesheets is to define new styles under a `styles` label. This is done through identation in RSON/YAML, while in TOML through `styles.this-style-name`. I think having to add this `styles.` prefix to each style adds noise with no added clarity.

I'm not aware of YAML's edge cases or why they wouldn't be a problem for rst2pdf though, so I'd be interested in hearing your thoughts on that.

**Comment by pmaupin** [comment]
It may be a good time to replace RSON.

Stylesheets were originally JSON, and at one point, I added a YAML option to rst2pdf for stylesheets. There were two issues at that time:

a) YAML parsing was slow.  Really slow.  A full rst2pdf regression run taking 30x longer slow.
b) When I dived into YAML, I found lots of incompatible implementations, and there were some edge-cases where it was not actually a strict superset of JSON.

So, RSON was developed specifically for this use-case:

https://groups.google.com/g/rst2pdf-discuss/c/48NTjPbuGLM?pli=1

It would not surprise me if all the YAML issues have now been fixed.  Or not.  I'm hard to surprise these days.

However, at the time, RSON solved both of these issues.  In point of fact, and to Rob's point about conversion, if there is something better, then the RSON stylesheets contain the seeds of their own destruction, because:

1) RSON is inherently round-trippable to JSON; and
2) Anything that is "better" damn well better have that same property.

Regards,
Pat

**Comment by pmaupin** [comment]
The initial stylesheets were in JSON.  When we decided to add YAML, we needed a rst2pdf command-line option to support it, because the python YAML parser at that time would not actually parse the old JSON stylesheets, despite the fact that YAML 1.2 was supposed to be fully JSON compatible.

IOW, at that time YAML was slow, unwieldy, and buggy.  It was not that difficult to create something faster and smaller that allowed readable stylesheets that _also_ fully supported preexisting JSON stylesheets, so that is what I did, and I yanked the YAML option because it was not something we wanted to waste regression time on.

If YAML is better now (as I defined above) and always available, we could certainly use it.  I had a look at TOML.  Not sure why we would do that at all.  A lot more busy syntax, to what end?

**Comment by lornajane** [comment]
OK I am seeing a yaml consensus here. Let's try to create a proof of concept for this between us when we can? I think if we are going to change this then we should try to get started.

**Comment by Simran-B** [comment]
> the YAML example in this thread is invalid for this reason

Because the first color value isn't quoted (`#` starts a single line comment):

```
pygments-bp: {parent: code, textColor: #007020}
```

Works if you change it to `textColor: "#007020"`.


> I'm not aware of YAML's edge cases or why they wouldn't be a problem for rst2pdf though

Some YAML gotchas that come to mind:

- `#` requires quoting (see above) or a literal block:

  ```yaml
  textColor: >-
    #007020
  ```

- Similarly, `: ` &nbsp;(that is a colon and a space) are disallowed. It's fine to use a colon in plain strings as long as it is not the first character or followed by whitespace however.
  - Error: `foo: bar: baz`
  - Okay: `foo: bar:baz`
  - Okay: `foo: 'bar: baz'`
  - Okay: `foo: "bar: baz"`
  - Varying parser behavior: `foo :bar` (either a string `bar` or `:bar`)
  - Error: `foo: :`

- Strings must be quoted if the start with a `&` or `*`, because these characters have special meaning (anchor/pointer).
  - `foo: &ref bar` - plain string `bar` with an anchor definition
  - `foo: "&ref bar"` - quoted string `&ref bar`
  - `foo: &ref` - empty string with an anchor definition
  - `foo: '&ref'` - quoted string `&ref`
  - The anchor can be used like: `baz: *ref` (baz will have a string value of `bar`)

- Leading exclamation marks have special meaning. They are used to explicitly tag values with data types (think of them as parser hints to translate YAML to specialized data structures). You may quote strings to avoid this behavior.
  - `foo: !bar` - empty string with explicit tag
  - `foo: "!bar"` - quoted string `!bar`
  - `foo: '!!binary YmFy'` - quoted string `!!binary YmFy`
  - `foo: !!binary YmFy` - `bar` encoded in base64. There seems to be parser-specific behavior here. One YAML to JSON converter casts it to a string `bar`, whereas one YAML online validator returns `[ 98, 97, 114 ]` instead.

- A leading question mark followed by whitespace is reserved for complex mapping keys.
  - Error: `foo: ?`
  - Error: `foo: ? bar`
  - Okay: `foo: bar?`
  - Okay: `foo: ?bar`
  - Non-primitive key (array) mapped to a string:
    ```yaml
      ? [foo, bar]
      : baz
      ```
  - Multi-line flow scalar string `? [foo, bar] : baz`:
    ```yaml
    foo: "\
      ? [foo, bar]
      : baz"
    ```
- Some parsers support the merge operator `<<`, so you may have to quote `<<` if you want to use it as literal key.

  ```yaml
  &ref
  foo: bar
  baz:
    <<: *ref
  ```

  ```json
  {
    "foo": "bar",
    "baz": {
      "foo": "bar"
    }
  }
  ```

---

Compared to RSON, the only real downside seems to be the need to quote `#`. Unquoted strings like `100%` are fine, and everything else I see in the default stylesheet should work without a change (except hex colors). Depending on the parser features, rst2pdf could support anchors and the merge operator, but neither is really needed IMO.
