### ISSUE TITLE
Stylesheet code examples are in JSON in the manual, while in RSON in the style files

### ISSUE THREAD

**Issue by nfraprado** [rst2pdf/rst2pdf#906]
Stylesheet code examples are in JSON in the manual, while in RSON in the style files and [examples page](https://rst2pdf.org/examples).
Is there some reason for this?

Even though that is valid since both formats are supported, I think it is confusing, specially since users tend to base their style files on the ones provided from installation and from the examples page, and then use the styling code from the manual to add any additional customization.
So making the formats different in those two places makes them incompatible and confusing to the users.

I think RSON would be the preferred format since it is cleaner, and it is already used in every place other than the manual.

If you agree with my point I can send a PR changing the stylesheet code snippets in the manual to be in RSON instead of JSON.

**Comment by lornajane** [comment]
This is a really good point, thanks for opening this issue! However I know that the style files may get an update (see #876 ) so let's make sure we update the manual style examples after that happens.

I'm pleased you created an issue before doing the work on the pull request - not because it wouldn't have been a definite improvement, but because your work might have been short-lived. If you have opinions on the style format, feel free to chime in on the other issue! We can revisit this after that one has been dealt with.
