### ISSUE TITLE
Small table overflowing page

### ISSUE THREAD

**Issue by nfraprado** [rst2pdf/rst2pdf#967]
A small table is considered too large for any frame.

**Description of problem**

Building the pdf for the following document:

```
PDF Documents From Your Text Editor
###################################

=  =======================================
0  Register as a non-blocking blk-mq drive
1  Register as a blocking blk-mq driver de
=  =======================================
```

Gives the following error:

```
Traceback (most recent call last):
  File "/usr/bin/rst2pdf", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/rst2pdf/createpdf.py", line 1683, in main
    RstToPdf(
  File "/usr/lib/python3.9/site-packages/rst2pdf/createpdf.py", line 659, in createPdf
    pdfdoc.multiBuild(elements)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/doctemplate.py", line 1167, in multiBuild
    self.build(tempStory, **buildKwds)
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/doctemplate.py", line 1080, in build
    self.handle_flowable(flowables)
  File "/usr/lib/python3.9/site-packages/rst2pdf/createpdf.py", line 813, in handle_flowable
    self.handle_frameEnd()
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/doctemplate.py", line 726, in handle_frameEnd
    self.handle_pageEnd()
  File "/usr/lib/python3.9/site-packages/reportlab/platypus/doctemplate.py", line 668, in handle_pageEnd
    raise LayoutError(ident)
reportlab.platypus.doctemplate.LayoutError: More than 10 pages generated without content - halting layout.  Likely that a flowable is too large for any frame.
```

Even though the table is small, both in width and in height, it is considered too large for any page and causes rst2pdf to abort.

Removing a single character from the table, it now becomes small enough to fit the page and the pdf is generated. But seeing the result pdf, it is clear that the table should have fitted with that extra character:

![Table working](https://user-images.githubusercontent.com/43095212/103144070-f243c880-4701-11eb-822e-aed02568e08c.png)

🖥 **Versions**

`python -V`: 3.9.1

`pip freeze | grep rst2pdf`: 0.98

`pip freeze | grep reportlab`: 3.5.57

Which operating system are you using? Archlinux

**Comment by nfraprado** [comment]
This may be related to #966, since both have to do with size calculation for tables.

**Comment by mchehab** [comment]
Based on my experience fixing troubles with LaTeX -> PDF output, for `rst2pdf` to work with the Linux Kernel docs, tables should:

1. calculate the size of each line, taking into account the type of font (as it can use a proportional-spaced font or a mono-space ones on literal texts);
2. scaled down - or have the font size reduced - in order to properly show all columns, on tables that require too wide lines;
3. broken into multiple pages, if it has more lines than available inside a page.

**Comment by lornajane** [comment]
This was a very interesting bug. I added some debugging (print statements!) to rst2pdf and followed the trail down into reportlab, which was calculating the height for this table as `2147483653.0` which .... seems large. Turns out what was really happening was:
 * rst2pdf tries to calculate table widths if they aren't defined in the style, in this case simply by counting characters and using that as the basis
 * we pass 2.5% and 97.5% in as our values - but this causes the left hand column to be 11.74 wide (what units are there? I am not sure, points?)
 * the padding on the default style is 6 each for left and right, causing a negative width to be passed forward to the bit that tries to fit the thing on the page - so it panics and returns a height of `0x7fffffff` - an error would be a lot more useful but there we are.

So the example with one less character makes a slightly wider first column that is just bigger than its padding and that works fine.

Ways to fix this: Set your column widths in the stylesheet, or put more characters in the left column. Or we could try to change our table width logic? I'm not sure if that makes sense or not but I tried anyway: #992

**Comment by mchehab** [comment]
>     * rst2pdf tries to calculate table widths if they aren't defined in the style, in this case simply by counting characters and using that as the basis

Just counting the number of characters is a bad idea. The Sphinx LaTeX table output does something that sounds similar to it, which cause tables to be badly formatted at the Linux Kernel docs, specially when the table contains both literals (with use monospaced fonts) and non-literals (which use proportional fonts). The best would be to take the character size when doing it.

>     * we pass 2.5% and 97.5% in as our values - but this causes the left hand column to be 11.74 wide (what units are there? I am not sure, points?)

I would guess that 11.74 would be cm, but that's just a wild guess ;-)

> 
>     * the padding on the default style is 6 each for left and right, causing a negative width to be passed forward to the bit that tries to fit the thing on the page - so it panics and returns a height of `0x7fffffff` - an error would be a lot more useful but there we are.


> 
> 
> So the example with one less character makes a slightly wider first column that is just bigger than its padding and that works fine.
> 
> Ways to fix this: Set your column widths in the stylesheet, or put more characters in the left column. 

There are tables at the Kernel that have lots of widths, at the media documentation, as they need to describe the bits on FOURCC formats  - with may have up to 32 bits - each with its own column, plus a long FOURCC macro name and the fourcc value. With LaTeX -> PDF, the only way to make them print is to reduce the font size and to change the padding on such tables via ".. raw:: latex" calls. Before doing this dirty trick, I tried to use a scale it down using LaTeX `\resizebox`. This worked for a while, but some changes during 1.x cycle broke support for it.

> Or we could try to change our table width logic? I'm not sure if that makes sense or not but I tried anyway: #992

I'll try your patch and check if it is now producing a decent output on those big tables.

**Comment by mchehab** [comment]
> You don't even need to put more characters in, just more `=` signs
> 
> e.g.
> 
> ```
> ======= =======================================
> 0       Register as a non-blocking blk-mq drive
> 1       Register as a blocking blk-mq driver de
> ======= =======================================
> ```
> 
> Will make the first column 15% wide compared to 2.5% if you use one `=` sign.

Good to know, although this sounds hackish.

The reasons why someone adds more or less '=' on each column at the sources are hardly linked to the size of each column at the final output.

For instance, I never use a single '=' on the files I write, as it sounds a way harder for reading a table ascii chart like:

```
= = =======================================
0 1 Register as a non-blocking blk-mq drive
1 2 Register as a blocking blk-mq driver de
= = =======================================
 ```

Than:


```
==   ==   =======================================
0     1   Register as a non-blocking blk-mq drive
1     2   Register as a blocking blk-mq driver de
==   ==   =======================================
```

Also, specially on tables with lots of lines, at least at the Kernel, we usually use fill the entire artwork to use either 79 or 80 columns just because this helps to avoid Sphinx warnings if a later change added something that would require more space.

So the above would likely be written as:

```
==   ==   =======================================================
0     1   Register as a non-blocking blk-mq drive
1     2   Register as a blocking blk-mq driver de
...
99   32   Something
==   ==   =======================================================

```

That doesn't mean that we want this at the output. It just means that it looks nicer
when someone is reading as a text file.

Also, when someone wants to enforce the size, the best is to use, instead:

```
.. tabularcolumns:: |p{7.0cm}|p{10.5cm}|
```
