### ISSUE TITLE
We should error if the stylesheet cannot be found

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#973]
At the moment, we generate a warning if the stylesheet cannot be found and then there may be an error generated later due to missing style definitions:

```
[WARNING] styles.py:654 Can't find stylesheet assets/manual.style
```

It would be better if we generated an error if the file is missing and we stopped processing at that point:

**Comment by lornajane** [comment]
I'm not sure I agree we should change what happens in this scenario. If I am trying to generate a PDF and I'm missing one (of possibly many) style file, I'd like rst2pdf to just give it a shot anyway - which is the current behaviour. Making it not work at all because of a missing style that maybe isn't even used seems like an unwelcome surprise to me.

**Comment by akrabat** [comment]
It's tricky because if you miss the warning the missing style can create a standard rst2pdf error with trace and then you're trying to debug what you did wrong in the rst file to cause the problem that the trace seems to indicate is the actual problem.

**Comment by lornajane** [comment]
The warning is there both for the missing stylesheet and for the missing style - and IMO this is the correct behaviour.

I agree that it can be hard to dig around the warning output if other errors cause the stack trace but I think styles should only trigger the warning, not cause the whole thing to give up. And since the warning is the current behaviour, a change from a PDF (that might be totally acceptable, depending what is missing) to no PDF is not a nice surprise.

**Comment by akrabat** [comment]
Closing based on Lorna's arguments.
